@baseURL=http://localhost:8080

### Test broker API
GET {{baseURL}}

### Auth Login API
POST {{baseURL}}/handle
Content-Type: application/json

{
    "action": "auth-login",
    "auth": {
        "email": "admin@example.com",
        "password": "verysecret"
    }
}

### Logger API
POST {{baseURL}}/handle
Content-Type: application/json

{
    "action": "log",
    "log": {
        "name": "first log",
        "data": "first log"
    }
}

### Mailer API
POST http://localhost:8080/handle
Content-Type: application/json

{
    "action": "mail",
    "mail": {
        "from": "from@example.com",
        "to": "john.smith@example.com",
        "subject": "This is subject",
        "message": "This is message"
    }
}

### RabbitMQ API
POST http://localhost:8080/handle
Content-Type: application/json

{
    "action": "log-mq",
    "log": {
        "name": "first log RabbitMQ",
        "data": "first log RabbitMQ"
    }
}

### RPC API
POST http://localhost:8080/handle
Content-Type: application/json

{
    "action": "log-rpc",
    "log": {
        "name": "first name RPC",
        "data": "first data RPC"
    }
}

### gRPC API
POST http://localhost:8080/handle
Content-Type: application/json

{
    "action": "log-grpc",
    "log": {
        "name": "first name gRPC",
        "data": "first data gRPC"
    }
}