@baseURL=http://localhost:8080

### Test broker API
GET {{baseURL}}

### Auth Login API
POST {{baseURL}}/handle
Content-Type: application/json

{
    "action": "auth-login",
    "auth": {
        "email": "admin@example.com",
        "password": "verysecret"
    }
}