services:
  broker:
    build:
      context: ./broker-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_URL: "amqp://admin:password@rabbitmq:5672/"
    depends_on:
      - auth
      - rabbitmq
  
  auth:
    build:
      context: ./auth-service
    restart: always
    ports:
      - "8081:8080"
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable connect_timeout=5"
    depends_on:
      - postgres

  logger:
    build:
      context: ./logger-service
    restart: always
    ports:
      - "8082:8080"
    environment:
      MONGO_URI: "mongodb://admin:password@mongo:27017/?authSource=admin"
      MONGO_DB: "logs"
    depends_on:
      - mongo
  
  mailer:
    build:
      context: ./mailer-service
    restart: always
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: none
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      FROM_FROM_NAME: "John Smith"
      FROM_FROM_ADDRESS: john.smith@example.com
      RABBITMQ_URL: "amqp://admin:password@rabbitmq:5672/"
    depends_on:
      - rabbitmq

  listener:
    build:
      context: ./listener-service
    restart: always
    environment:
      RABBITMQ_URL: "amqp://admin:password@rabbitmq:5672/"
    depends_on:
      - rabbitmq

  postgres:
    image: postgres:18.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"

  rabbitmq:
    image: rabbitmq:4-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  mongo_data:
  rabbitmq_data: