# Build
FROM golang:1.26-alpine as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o auth ./cmd/api

# Run
FROM alpine:latest
COPY --from=builder /app/auth .
EXPOSE 8080
CMD [ "./auth" ]