# Build
FROM golang:1.26-alpine as builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o listener ./cmd

# Run
FROM alpine:latest
COPY --from=builder /app/listener .
EXPOSE 8080
CMD [ "./listener" ]